#!/bin/sh
set -e
if command -v gradle >/dev/null 2>&1; then
  exec gradle "$@"
fi
echo "Gradle is not installed. Use the Gradle wrapper generated by the bootstrap task or install Gradle 8.10.2+." >&2
exit 1
